# Site settings
name: Sticky Pixel
title: Riviera Web Design and Development | Sticky Pixel
email: info@stickypixel.com
description: Sticky Pixel is a digital design agency relentless in the pursuit of creating beautiful, effortless experiences from our base in Nice on the French Riviera.
append_desc: ", a web design and development company covering Nice, Monaco, Antibes, Cannes, Juan-les-Pins."
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://www.stickypixel.com
author: Chris Sargent
keywords: web design development agency html css graphic design seo inbound marketing france 06 riviera antibes nice juan-les-pins monaco cannes alpes-maritimes english speaking
twitter_username: Chris5argent
github_username:  ChrisSargent
google_plus: StickyPixelRocks
linkedin_page: sticky-pixel
facebook_page: stickypixel
instagram_user: chris5argent
pinterest_user: stickypixel
youtube_user: stickypixelrocks
pinterest_verify: 185745922478d5e2f01bedcb16a93d11
bing_verify: B15758C08831D1D7033389623B947D8A
fb_app_id: 292220120802626
fb_admins: 731575475
fb_profile_id: 1599401430312734
og_image: http://www.stickypixel.com/img/sticky-pixel-og-image.jpg
og_logo: http://www.stickypixel.com/img/sticky-pixel-logo-square.jpg
telephone: +33 652 15 13 00
foundingDate: 2015-05-01
founder: Chris Sargent
address: 29 Crick Road, Rugby, Warwickshire, CV21 4DU
fraddress: Le Saphir, Rue Bricka, Juan&#8209;les&#8209;Pins, 06160&nbsp;France
legal_name: Sticky Pixel Ltd
company_no: 6849452
assets: '/assets'

# Build settings
markdown: kramdown
source: src
destination: dist
exclude: [assets]
keep_files: [assets]
incremental: false
collections:
  home:
    output: true
  team:
    output: true

landing_links:
  - url: ""
    text: Home
  - url: "#about"
    text: About Us
  - url: "#services"
    text: Services
  - url: "#team"
    text: Team
  - url: "careers/front-end-developer.html"
    text: Careers
  - url: "articles/free-fridays.html"
    text: Free Fridays
  - url: "#contact"
    text: Contact Us
